# Site settings
title: Mark Smith's Blog
email: markjgsmith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an independant software developer and digital nomad. I write
  about my adventures on this blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.markjgsmith.com" # the base hostname & protocol for your site
twitter_username: markjgsmith
github_username:  mjgs

# Build settings
markdown: kramdown
timezone: Asia/Bangkok

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
