# Site settings
title: Mark Smith's Blog
email: markjgsmith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog written and published by Mark Smith, Freelance Web Developer, Consultant and Automation Engineer.
  Focusses on javascript, technology and web development with some other bits and pieces mixed in. 
  There is also a daily linkblog, a weekly newsletter and an experimental podcast.
  For freelance and sponsorship enquiries contact via email. See website for details.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.markjgsmith.com" # the base hostname & protocol for your site
twitter_username: markjgsmith
github_username:  mjgs

# SEO plugin
tagline: Petsonal blog of Mark Smith, Freelance Web Developer, Consultant and Automation Engineer
author: Mark Smith
twitter:
  username: markjgsmith
  card: summary
social:
  name: Mark Smith
  links:
    - https://twitter.com/markjgsmith
    - https://www.linkedin.com/in/markjgsmith
    - https://github.com/mjgs
    - https://dev.to/mjgs
    - https://www.indiehackers.com/mjgs

# Build settings
markdown: kramdown
timezone: Asia/Bangkok

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

minima:
  date_format: "%B %-d, %Y"
